# Default values for image-tiler.
replicaCount: 1

imageConfig:
  pullPolicy: IfNotPresent

volumeClaim: ceres-flights

port: 8888
  
nodeEnv: development
host: "0.0.0.0"
port: "80" # keep in sync with values.yaml
rootPath: "/flights" # keep in sync with values.yaml
