# Default values for image-tiler.
replicaCount: 1

imageConfig:
  pullPolicy: IfNotPresent

volume:
  mountPath: "/flights"
  name: flights-vol
  claim: flights-dir-claim
  hostPath: "/tmp/hostpath_pv"
  storage: 1Gi
  storageClass: pv
  accessModes: ReadWriteOnce

service:
  type: LoadBalancer
  externalPort: 8888
  internalPort: 80
  