apiVersion: v1
kind: Service
metadata:
  name: tiler
spec:
  ports:
  - port: 8888
    targetPort: 80
  type: LoadBalancer
  selector:
    app: tiler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiler
spec:
  selector:
    matchLabels:
      app: tiler
  template:
    metadata:
      labels:
        app: tiler
    spec:
      containers:
      - name: tiler
        image: image_tiler_2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/flights"
          name: flights-vol
      volumes:
        - name: flights-vol
          persistentVolumeClaim:
            claimName: flights-dir-claim
