apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "image-tiler.fullname" . }}
  labels:
    app: {{ template "image-tiler.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "image-tiler.fullname" . }}  
              servicePort: {{ .Values.port }}
